name: Download x-ui Release

on:
  workflow_dispatch:

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download x-ui-linux-amd64.tar.gz
        run: |
          mkdir -p downloads
          curl -L "https://github.com/MHSanaei/3x-ui/releases/download/v3.0.1/x-ui-linux-amd64.tar.gz" -o downloads/x-ui-linux-amd64.tar.gz

      - name: Commit and Push File
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add downloads/x-ui-linux-amd64.tar.gz
          git commit -m "Add x-ui-linux-amd64.tar.gz"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

